# Generated by Django 4.2.3 on 2023-07-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='customer_number',
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_name',
            field=models.CharField(default='jhon', max_length=100),
            preserve_default=False,
        ),
    ]
